#faça um programa que leia um numero inteiro qualquer e mostre na tela sua tabuada

tabuada = int(input('Digite um número para saber a tabuada:'))
print('-' * 13)
print(' {} x {:2} = {}'.format (tabuada, 1, tabuada *1))
print(' {} x {:2} = {}'.format (tabuada, 2, tabuada *2))
print(' {} x {:2} = {}'.format (tabuada, 3, tabuada *3))
print(' {} x {:2} = {}'.format (tabuada, 4, tabuada *4))
print(' {} x {:2} = {}'.format (tabuada, 5, tabuada *5))
print(' {} x {:2} = {}'.format (tabuada, 6, tabuada *6))
print(' {} x {:2} = {}'.format (tabuada, 7, tabuada *7))
print(' {} x {:2} = {}'.format (tabuada, 8, tabuada *8))
print(' {} x {:2} = {}'.format (tabuada, 9, tabuada *9))
print(' {} x {:2} = {}'.format (tabuada, 10, tabuada *10))
print('-' * 13)